#############################################################################
# Makefile for building: DragFile.app/Contents/MacOS/DragFile
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  DragFile.pro
# Template: app
# Command: /Users/Yaoyao/Qt5.5.1/5.5/clang_64/bin/qmake -o Makefile DragFile.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = icpc
CXX           = icpc
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fopenmp -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -fopenmp  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers -I../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../../Qt5.5.1/5.5/clang_64/mkspecs/macx-clang -F/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib
QMAKE         = /Users/Yaoyao/Qt5.5.1/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DragFile1.0.0
DISTDIR = /Users/Yaoyao/Documents/Code/DragFile/DragFile/.tmp/DragFile1.0.0
LINK          = icpc
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib -fopenmp -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		DragFile.cpp \
		qfiletextedit.cpp qrc_dragfilerc.cpp \
		moc_DragFile.cpp \
		moc_qfiletextedit.cpp
OBJECTS       = main.o \
		DragFile.o \
		qfiletextedit.o \
		qrc_dragfilerc.o \
		moc_DragFile.o \
		moc_qfiletextedit.o
DIST          = ../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/uic.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/lex.prf \
		DragFile.pro DragFile.h \
		qfiletextedit.h main.cpp \
		DragFile.cpp \
		qfiletextedit.cpp
QMAKE_TARGET  = DragFile
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = DragFile.app/Contents/MacOS/DragFile

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_DragFile.h $(OBJECTS)  
	@test -d DragFile.app/Contents/MacOS/ || mkdir -p DragFile.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DragFile.pro ../../../../Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/qdevice.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/unix.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/mac.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/macx.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/clang.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/qconfig.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/resources.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/moc.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/uic.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/lex.prf \
		DragFile.pro \
		dragfilerc.qrc \
		/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile DragFile.pro
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/qdevice.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/device_config.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/unix.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/mac.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/macx.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/clang.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/qconfig.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/spec_post.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/default_post.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/qt.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/resources.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/moc.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/uic.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/yacc.prf:
../../../../Qt5.5.1/5.5/clang_64/mkspecs/features/lex.prf:
DragFile.pro:
dragfilerc.qrc:
/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DragFile.pro

qmake_all: FORCE

DragFile.app/Contents/PkgInfo: 
	@test -d DragFile.app/Contents || mkdir -p DragFile.app/Contents
	@$(DEL_FILE) DragFile.app/Contents/PkgInfo
	@echo "APPL????" > DragFile.app/Contents/PkgInfo
DragFile.app/Contents/Resources/empty.lproj: 
	@test -d DragFile.app/Contents/Resources || mkdir -p DragFile.app/Contents/Resources
	@touch DragFile.app/Contents/Resources/empty.lproj
	
DragFile.app/Contents/Info.plist: 
	@test -d DragFile.app/Contents || mkdir -p DragFile.app/Contents
	@$(DEL_FILE) DragFile.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,SYSU.DragFile,g" -e "s,@ICON@,photosurface.icns,g" -e "s,@EXECUTABLE@,DragFile,g" -e "s,@TYPEINFO@,????,g" ../../../../Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >DragFile.app/Contents/Info.plist
DragFile.app/Contents/Resources/photosurface.icns: photosurface.icns
	@test -d DragFile.app/Contents/Resources/ || mkdir -p DragFile.app/Contents/Resources/
	@$(DEL_FILE) DragFile.app/Contents/Resources/photosurface.icns
	@$(COPY_FILE) photosurface.icns DragFile.app/Contents/Resources/photosurface.icns

all: Makefile \
		DragFile.app/Contents/PkgInfo \
		DragFile.app/Contents/Resources/empty.lproj \
		DragFile.app/Contents/Info.plist \
		DragFile.app/Contents/Resources/photosurface.icns $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dragfilerc.qrc $(DISTDIR)/
	$(COPY_FILE) --parents DragFile.h qfiletextedit.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp DragFile.cpp qfiletextedit.cpp $(DISTDIR)/
	$(COPY_FILE) --parents DragFile.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r DragFile.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_dragfilerc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_dragfilerc.cpp
qrc_dragfilerc.cpp: dragfilerc.qrc \
		photosurface.icns
	/Users/Yaoyao/Qt5.5.1/5.5/clang_64/bin/rcc -name dragfilerc dragfilerc.qrc -o qrc_dragfilerc.cpp

compiler_moc_header_make_all: moc_DragFile.cpp moc_qfiletextedit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_DragFile.cpp moc_qfiletextedit.cpp
moc_DragFile.cpp: ../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		DragFile.h
	/Users/Yaoyao/Qt5.5.1/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/mkspecs/macx-clang -I/Users/Yaoyao/Documents/Code/DragFile/DragFile -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib DragFile.h -o moc_DragFile.cpp

moc_qfiletextedit.cpp: ../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/QDropEvent \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/QDragEnterEvent \
		qfiletextedit.h
	/Users/Yaoyao/Qt5.5.1/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/mkspecs/macx-clang -I/Users/Yaoyao/Documents/Code/DragFile/DragFile -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/Yaoyao/Qt5.5.1/5.5/clang_64/lib qfiletextedit.h -o moc_qfiletextedit.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_DragFile.h
compiler_uic_clean:
	-$(DEL_FILE) ui_DragFile.h
ui_DragFile.h: DragFile.ui \
		qfiletextedit.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/QDropEvent \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/QDragEnterEvent
	/Users/Yaoyao/Qt5.5.1/5.5/clang_64/bin/uic DragFile.ui -o ui_DragFile.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp DragFile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DragFile.o: DragFile.cpp DragFile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_DragFile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/QtCore \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qanimationgroup.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qparallelanimationgroup.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpauseanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsequentialanimationgroup.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvariantanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtextcodec.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcompilerdetection.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qendian.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qflags.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qglobalstatic.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qisenum.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlibraryinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qprocessordetection.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsystemdetection.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtypeinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtypetraits.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbuffer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdatastream.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdiriterator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfiledevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfileselector.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfilesystemwatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qiodevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlockfile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qloggingcategory.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qresource.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsavefile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstorageinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtemporarydir.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtemporaryfile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qurlquery.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractproxymodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qidentityproxymodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsortfilterproxymodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringlistmodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsonvalue.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstracteventdispatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractnativeeventfilter.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbasictimer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qeventloop.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmimedata.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qobjectcleanuphandler.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsharedmemory.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsocketnotifier.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsystemsemaphore.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qwineventnotifier.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmimedatabase.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmimetype.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfactoryinterface.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlibrary.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qplugin.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpluginloader.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/quuid.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractstate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstracttransition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qeventtransition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfinalstate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qhistorystate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsignaltransition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstatemachine.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qatomic.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qexception.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfutureinterface.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfuturesynchronizer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfuturewatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qgenericatomic.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qreadwritelock.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qresultstore.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qrunnable.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsemaphore.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qthreadpool.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qthreadstorage.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qalgorithms.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qarraydata.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qarraydataops.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qarraydatapointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbitarray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbytearray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraylist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraymatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcache.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qchar.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcollator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineoption.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineparser.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcontainerfwd.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcontiguouscache.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcryptographichash.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qeasingcurve.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qhash.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qiterator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qline.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlinkedlist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlocale.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmargins.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmessageauthenticationcode.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qqueue.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qrefcount.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qscopedpointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qscopedvaluerollback.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qset.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qshareddata.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstack.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringbuilder.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringmatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtextboundaryfinder.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtimezone.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvarlengtharray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DragFile.o DragFile.cpp

qfiletextedit.o: qfiletextedit.cpp qfiletextedit.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/QTextEdit \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/Headers/qtextedit.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/QString \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/QDropEvent \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtGui.framework/Headers/QDragEnterEvent \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/QtCore \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qanimationgroup.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qparallelanimationgroup.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpauseanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsequentialanimationgroup.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvariantanimation.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtextcodec.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcompilerdetection.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qendian.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qflags.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qglobalstatic.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qisenum.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlibraryinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qprocessordetection.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsystemdetection.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtypeinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtypetraits.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbuffer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdatastream.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdiriterator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfiledevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfileselector.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfilesystemwatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qiodevice.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlockfile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qloggingcategory.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qresource.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsavefile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstorageinfo.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtemporarydir.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtemporaryfile.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qurlquery.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractproxymodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qidentityproxymodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsortfilterproxymodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringlistmodel.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qjsonvalue.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstracteventdispatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractnativeeventfilter.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbasictimer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qeventloop.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmimedata.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qobjectcleanuphandler.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsharedmemory.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsocketnotifier.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsystemsemaphore.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qwineventnotifier.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmimedatabase.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmimetype.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfactoryinterface.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlibrary.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qplugin.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpluginloader.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/quuid.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstractstate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qabstracttransition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qeventtransition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfinalstate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qhistorystate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsignaltransition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstate.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstatemachine.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qatomic.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qexception.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfutureinterface.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfuturesynchronizer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qfuturewatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qgenericatomic.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qreadwritelock.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qresultstore.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qrunnable.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsemaphore.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qthreadpool.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qthreadstorage.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qalgorithms.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qarraydata.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qarraydataops.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qarraydatapointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbitarray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbytearray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraylist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraymatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcache.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qchar.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcollator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineoption.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineparser.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcontainerfwd.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcontiguouscache.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qcryptographichash.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qeasingcurve.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qhash.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qiterator.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qline.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlinkedlist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qlocale.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmargins.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qmessageauthenticationcode.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qqueue.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qrefcount.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qscopedpointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qscopedvaluerollback.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qset.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qshareddata.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstack.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringbuilder.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qstringmatcher.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtextboundaryfinder.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtimezone.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvarlengtharray.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../../Qt5.5.1/5.5/clang_64/lib/QtCore.framework/Headers/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qfiletextedit.o qfiletextedit.cpp

qrc_dragfilerc.o: qrc_dragfilerc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_dragfilerc.o qrc_dragfilerc.cpp

moc_DragFile.o: moc_DragFile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DragFile.o moc_DragFile.cpp

moc_qfiletextedit.o: moc_qfiletextedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qfiletextedit.o moc_qfiletextedit.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

